# this pipeline should not be run on version tag releases (it may cause a non correct sha to override version tagged image in dockerhub)
version: "1.0"

stages:
- CI
- CD

steps:

  install_dependencies:
    title: 'Installing testing dependencies'
    stage: CI
    image: codefresh/node-tester-image:8.8.0
    commands:
        - yarn install --frozen-lockfile

  eslint:
    title: 'Running linting logic'
    stage: CI
    image: codefresh/node-tester-image:8.8.0
    commands:
        - yarn eslint

  unit-tests:
    stage: CI
    title: 'Running unit tests'
    image: codefresh/node-tester-image:8.8.0
    commands:
        - yarn test

  add_git_tag:
    title: "Add Git tag"
    stage: CD
    image: codefresh/cli
    commands:
    - 'apk update && apk add jq'
    - 'export PACKAGE_VERSION=$(jq -r ".version" package.json)'
    - "echo Current version: $PACKAGE_VERSION"
    - "cf_export PACKAGE_VERSION"
    - "git tag $PACKAGE_VERSION"
    when:
      branch:
        only: [ master ]

  create_release:
    stage: CD
    title: "Create github release"
    image: codefresh/cli-build
    commands:
    - 'curl --fail -X POST -d ''{"tag_name":"v${{PACKAGE_VERSION}}","target_commitish":"${{CF_REVISION}}","name":"Codefresh V${{PACKAGE_VERSION}}"}'' -H "Content-Type: application/json" -H "Authorization: token ${{GITHUB_TOKEN}}" https://api.github.com/repos/codefresh-io/sdk/releases'
    when:
      branch:
        only: [ master ]

  deploy_to_npm:
    stage: CD
    title: "Publishing To Npm"
    image: codefresh/npm-publish:master
    commands:
    - NPM_TOKEN=${{NPM_TOKEN}} npm run ci-publish
    when:
      branch:
        only: [ master ]
